- docker_compose:
    project_name: odoo
    definition:
      version: '2'
      services:
        web:
          image: odoo:12.0
          container_name: web
          depends_on:
            - db
          ports:
          - "8069:8069"
          environment:
          - HOST=db
          - USER=odoo
          - PASSWORD="{{ odoo_pass }}"
        db:
          image: postgres:10
          container_name: db
          environment:
          - POSTGRES_DB=postgres
          - POSTGRES_PASSWORD=odoo
          - POSTGRES_USER="{{ odoo_pass }}"

